### ISSUE TITLE
Vagrant VM Depreciated? 

### ISSUE THREAD

**Issue by zrichmond** [xtuple/xtuple-vagrant#63]
Just wondering if this has been more or less depreciated?  Personally, I've just been installing xtuple-server via the bootstrap directly on VMs (virtual box or google compute engine) but that has just been for pre-upgrade testing.  I am wondering what you are doing internally for development now, so I can begin to setup my dev environment the same.  Any pointers would be great, thanks, Zak

**Comment by bixwilson** [comment]
Hi Zak. The answer is yes, xtuple-server is all-but-officially deprecated. This week we will be making the change to redirect people to our new recommended toolkit, http://github.com/xtuple/xtuple-admin-utility/wiki. Please feel free to check it out and give us your feedback. Thanks.
